### ISSUE TITLE
[Proposal] Proxy Voting

### ISSUE THREAD

**Issue by cryptokat** [semuxproject/semux-core#167]
For compounding block rewards, users have to access their wallet frequently to manually sign vote transactions if they don't feel comfortable saving their private keys on a remote server as it might increase the risk of getting funds stolen. By delegating the permission of voting to a proxy account, users will be able to re-vote through automated programs without putting their funds at risks.

#### Todos

- [ ] Implement new transaction types `ASSIGN_VOTING_PROXY`, `CANCEL_VOTING_PROXY`, `PROXY_VOTE`, `PROXY_UNVOTE`
- [ ] Allow an assigned voting proxy to vote/unvote on behalf of its assigner
- [ ] Initiate a fork to enable proxy voting

**Comment by telllic** [comment]
Is it possible to solve using smart contracts? Also I think, after the release of a standalone light wallet, this problem will not be relevant.

**Comment by honeycrypto** [comment]
@telllic if I understood correctly, this will also allow automated public pools which can proportionally rebalance votes between multiple validators. This was a long time desired feature.

**Comment by cryptokat** [comment]
@telllic It's not possible to achieve this through smart contract/light wallet as the current consensus does not allow an account to vote for others.

**Comment by orogvany** [comment]
If I were able to steal your proxy voting creds, I could still steal your funds though with this.  In a slow way.  Vote/unvote costs sem. So timing rapid vote/unvote of tiny amount at time when either my validator, a pool I vote for, or a validator I vote with your sem to avoid detection.

**Comment by honeycrypto** [comment]
@orogvany well, simply grant voting rights only to reliable pools. Revoke it, if the pool start misbehaving (like move coins to a different pub address).

Also, pretty much all other PoS/BFT projects have locking period of 21-28 days. I recall that everyone was against it, maybe a good time to discuss it again?

**Comment by honeycrypto** [comment]
The controversial idea of introducing locking period can be a good use case for testing On-chain Governance from #164. 

PoS with locking period = more skin in the game. Voters can enjoy 40%+ of passive income yearly, but they must accept the risk to miss profits via trading if their coins are locked and the price start rising dramatically.

**Comment by orogvany** [comment]
Whitelisting which pools are allowed to a delegate would help, I agree. But would require more calls than proposed.

Still would be able to empty someone's account, unless a lock period was added as you say.

I think the inconvienice of lock periods would diminish the benefits, and add overhead to block proposals.  I'm open to consideration, just trying to think of ramifications.

**Comment by orogvany** [comment]
Wouldn't just adding vote/unvote to supported vm calls be a better way to manage such, and have benefits beyond what this supplies?

**Comment by cryptokat** [comment]
Thanks for your feedback @orogvany. I am not really sure how this can be done through a smart contract. Doesn't contract call still require access to a voter's private key?

**Comment by orogvany** [comment]
One could set up a smart contract that can allow vote actions from one address, but only withdrawals to another that I believe would meet these needs and give more flexibility.  It would also allow things like send funds to this contract for a t manage voting for best payout, and you can withdraw, but the funds would be managed by a third party for purposes of voting. Would also allow for whatever min/max vote locking it wanted, rather than just enforcing some static blanket rules

**Comment by semuxgo** [comment]
You won't be able to do that directly with the EVM, but there are workarounds:
- Add new opcodes to deal with unvote/unvote
- Add a pre-compiled contract 

The coins need to be in the custody of the contract though.

**Comment by orogvany** [comment]
Sorry, yes I was referring to adding vote/unvote opcodes

No need for precompiled contract.  Folks can deploy their own as necessary to meet their needs. Or a basic one can just be deployed, but I can think of several variations that users might desire.  Eg basic one, time locked/rate limited. Only allowing select sets of voting targets, 3rd party managed voting (like voting for animal pools many nodes balancing, or voting for highest payouts pub pools), etc

**Comment by orogvany** [comment]
Same would likely go for voting for onchain governance voting..  VM contract would supplant need to implement it natively, and keep codebase less bloated.  Easy to change for future needs with new contract rather than keep forking

**Comment by cryptokat** [comment]
@orogvany @semuxgo Thanks for the hint. It makes a lot more sense to me now.

A voting proxy contract would probably look like this if I understand you correctly:
```solidity
contract VotingProxy {

    address payable public owner;
    
    // the proxy address that is going to vote on behalf of the owner
    address public proxy;

    constructor(address _proxy) public {
        owner = msg.sender;
        proxy = _proxy;
    }

    // withdrawal tokens to the owner's account
    function withdrawal(uint256 amount) public {
        require(msg.sender == owner);
        owner.transfer(amount);
    }
    
    function vote(address delegate, uint256 amount) public {
        require(msg.sender == proxy || msg.sender == owner);
        delegate.vote(amount); // the vote opcode needs to be added
    }

    // contract owner needs to deposit tokens into the contract after creation
    function() external payable {}
}
```

**Comment by cryptokat** [comment]
What are the efforts that need to be done for adding the `vote` opcode? Is there any prior work that I can refer to?

**Comment by orogvany** [comment]
Checkout the eth precompiled contract opcodes for like sha256 in Precompiled contracts.java in evm module.  We will need to define a dataword for vote/unvote and implement.  We will need to do some refactor to allow injection of block chain or other resources.  Sadly as precompiled contracts are created by static method, we would probably start with making that more like a factory than static provider so we could add semux specific in semux rather than tainting the generic vm module.  Sorry if that doesn't make sense, on mobile. Can clarify later.

**Comment by orogvany** [comment]
I can help get framework laid for it tonight.  I had looked into it a bit a few months ago

**Comment by cryptokat** [comment]
@orogvany Sounds cool. Thanks alot!

**Comment by orogvany** [comment]
Started 
https://github.com/semuxproject/semux-core/pull/168
https://github.com/semuxproject/evm/pull/15

To actually implement vote/unvote will need more context in precompiledContract interface call.  All the other calls do not change state, so it was unnecessary in original implementation.  Certainly a lot to do to implement, a bit more than I anticipated, as Eth doesn't have a notion of DelegateState for us to implement, so some scope will need to creep into eth module, but trying to keep semux core code separate from the evm module.

**Comment by orogvany** [comment]
Vote/Unvote Precompiled contracts now complete/merged!

Can't wait to see how it gets used!  Calling this good.
