### ISSUE TITLE
v1.5.0 Meta Issue

### ISSUE THREAD

**Issue by semuxgo** [semuxproject/semux-core#172]
Here are the main features I want to push for the next release:

- [ ] HD wallet with Ledger support #171 
- [x] Reset the `testnet` with new seeds, with additional precompiled contracts, like #168
- [ ] Split the GUI from the core, potentially `semux-wallet`
- [ ] Apply a database upgrade based on #160
- [ ] Complete the fast-sync P2P messages

**Comment by semuxgo** [comment]
Updates:

- HD implementation with Ledger support is ready, we just need to decide whether to use SLIP10 or BIP32-Ed25519 as the default solution;
- Testnet is reluanched!

**Comment by semuxgo** [comment]
Use milestone instead.
