### ISSUE TITLE
Semux 2.0 Release Checklist

### ISSUE THREAD

**Issue by semuxgo** [semuxproject/semux-core#248]
- [x] Enable the VM fork signal on Mainnet;
- [x] Make a new binary release;
- [ ] Address the vote/unvote traceability issue by witoldsz (see #249);
- [x] Address the late-upgrade issue by orogvany (see #250);
- [x] Update semux-js.

Please comment any missing issues below for Semux 2.0 release.

**Comment by witoldsz** [comment]
@orogvany said once, he has addressed the issue to insert votes, unvotes, transfers, etc. into the database so thet would appear as regular actions. It could be enabled by each user individually, because not everyone needs it (it takes more db space).

I would enable it for my api.semux.online services, so it could be used by various pool calculators (including two of mine :)
